name = "MimiqCircuitsBase"
uuid = "3a95eabf-73f4-453e-aae8-8a11a27ac032"
authors = ["Guido Masella <guido.masella@gmail.com>"]
version = "0.2.3"

[deps]
BiMaps = "02e1a8d2-c0bf-449f-9d6e-85b4cfc6bdab"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
